name: "Compilation test"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:bookworm
    steps:
      - uses: actions/checkout@v4
      - name: install prerequisites
        timeout-minutes: 10
        run: |
          apt-get -qq update
          apt-get -qq install -y build-essential
      - name: attempt compilation w/o asan
        timeout-minutes: 2
        run: |
          NO_ASAN=1 make -B ansi2html
      - name: attempt compilation with asan
        timeout-minutes: 2
        run: |
          make clean
          make -B ansi2html
      - name: run tests
        timeout-minutes: 1
        run: |
          make run-tests
      - name: test minimal conversion
        timeout-minutes: 1
        run: |
          printf '\e[0;31mred\e[0;1;31mbold red\e[0m' | ./ansi2html -p vga
          echo
          printf '\e[0;31mred\e[0;1;31mbright red\e[0m' | ./ansi2html -b -p vga
          echo
  build-static:
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - uses: actions/checkout@v4
      - name: install prerequisites
        timeout-minutes: 10
        run: |
          apk add --no-cache clang musl-dev binutils xz nodejs
      - name: static compilation with clang/musl
        timeout-minutes: 2
        run: |
          clang -O2 -o ansi2html -static -Wl,-strip-all -Wl,-static src/ansi2html.c src/main.c src/structs/ansi_color_palette.c src/structs/ansi_color_type.c src/structs/ansi_fg_or_bg.c
      - name: test minimal conversion
        timeout-minutes: 1
        run: |
          printf '\e[0;31mred\e[0;1;31mbold red\e[0m' | ./ansi2html -p vga
          echo
          printf '\e[0;31mred\e[0;1;31mbright red\e[0m' | ./ansi2html -b -p vga
          echo
      - name: compress binary
        timeout-minutes: 1
        run: xz --compress --stdout ansi2html > ansi2html.xz
